enum Textures {

    BackgroundBase = "BackgroundBase",
    BackgroundGame = "BackgroundGame",
    BackgroundGameIntro = "BackgroundGameIntro",
    BackgroundGameOutro = "BackgroundOutro",
    BackgroundSlide1 = "BackgroundSlide1",
    BackgroundSlide2 = "BackgroundSlide2",
    ImageEndScene = "ImageEndScene",
    ImageTest1 = "ImageTest1",
    ImageTest2 = "ImageTest2",
    ImageTest3 = "ImageTest3",
    ImageTest4 = "ImageTest4",
    ImageTest5 = "ImageTest5",
    ImageTest6 = "ImageTest6",
    TutorialTest1 = "Tutorial1",
    TutorialTest2 = "Tutorial2",
    TutorialTest3 = "Tutorial4",
    TutorialTest4 = "Tutorial3",
    TutorialTest5 = "Tutorial5",
    TutorialTest6 = "Tutorial6",
    GreenBar = "GreenBar",
    Popup = "HeadsUp",
    MenuPanel = "MenuPanel",
    Pausebutton = "PauseButton",
    Debugbutton = "DebugButton",
    MenuButton = "MenuButton",
    Checkmark = "Checkmark",
    AnswerBox = "answerBox",
    CheckBox = "CheckBox",
    ScoreBox = "ScoreBox",
    TextBox = "TextBox",
    Right = "Right",
    Left = "Left",
    Ball = "ball",
    Block = "block",
    Paddle = "paddle",

}

export default Textures;
